#init boids
boids_number: 50
x_position_range: [-450,50.0]
y_position_range: [300.0,600.0]
x_velocity_range: [0,10.0]
y_velocity_range: [-20.0,20.0]

#update boids
flocking_coeff: 0.01
dispersion_threshold: 100
match_speed_threshold: 10000
match_speed_coeff: 0.125
