#init boids
boids_number: 50
x_position_range: [-450,50.0]
y_position_range: [300.0,600.0]
x_velocity_range: [0,10.0]
y_velocity_range: [-20.0,20.0]

#update boids
flocking_coeff: 0.01
dispersion_distance: 100
match_speed_distance: 10000
match_speed_coeff: 0.125

#plot boids
plot_dimensions:
    x: [-500, 1500]
    y: [-500, 1500]
animation:
    frames: 50
    interval: 50